#!/usr/bin/env python3
"""
Configuration Helper Script
Helps users set up their .env file interactively
"""

import os
from pathlib import Path


def print_banner():
    """Print welcome banner"""
    print("=" * 60)
    print("Azure Agent Framework Chat Bot - Configuration Helper")
    print("=" * 60)
    print()


def check_env_file():
    """Check if .env file exists"""
    env_path = Path(".env")
    env_example_path = Path(".env.example")
    
    if env_path.exists():
        print("⚠️  Warning: .env file already exists!")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            print("Exiting without making changes.")
            return False
    
    if not env_example_path.exists():
        print("❌ Error: .env.example file not found!")
        print("Make sure you're running this script from the project root directory.")
        return False
    
    return True


def get_user_input(prompt, default=None, required=True):
    """Get input from user with optional default"""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    while True:
        value = input(full_prompt).strip()
        
        if not value and default:
            return default
        
        if not value and required:
            print("This field is required. Please enter a value.")
            continue
        
        return value


def main():
    """Main configuration function"""
    print_banner()
    
    if not check_env_file():
        return
    
    print("This helper will guide you through setting up your .env file.")
    print("You'll need your Azure AI Foundry credentials ready.")
    print()
    print("Press Ctrl+C at any time to cancel.")
    print()
    
    # Get required configuration
    print("📝 Required Configuration:")
    print("-" * 60)
    
    endpoint = get_user_input(
        "Azure OpenAI Endpoint (e.g., https://my-resource.openai.azure.com/)",
        required=True
    )
    
    print()
    print("🔐 Authentication Mode:")
    print("  1. managed_identity - Uses Azure Managed Identity (Entra ID)")
    print("     Works automatically in App Service; locally uses 'az login'.")
    print("  2. api_key          - Uses an Azure OpenAI API key")
    print()
    auth_type_input = get_user_input(
        "Authentication Type (1 or 2)",
        default="1",
        required=False
    )
    auth_type = "api_key" if auth_type_input in ("2", "api_key") else "managed_identity"
    
    api_key = ""
    if auth_type == "api_key":
        api_key = get_user_input(
            "Azure OpenAI API Key",
            required=True
        )
    else:
        print("  → Using Managed Identity — no API key needed.")
    
    deployment_name = get_user_input(
        "GPT-5 Deployment Name (e.g., gpt-5-deployment)",
        required=True
    )
    
    api_version = get_user_input(
        "API Version",
        default="2025-06-01-preview",
        required=False
    )
    
    print()
    print("📝 Optional Configuration:")
    print("-" * 60)
    print("(Press Enter to skip)")
    print()
    
    subscription_id = get_user_input(
        "Azure Subscription ID",
        required=False
    )
    
    resource_group = get_user_input(
        "Azure Resource Group",
        required=False
    )
    
    project_name = get_user_input(
        "Azure AI Project Name",
        required=False
    )
    
    print()
    print("🤖 Agent Configuration:")
    print("-" * 60)
    
    agent_name = get_user_input(
        "Agent Name",
        default="ChatBot Agent",
        required=False
    )
    
    instructions_file = get_user_input(
        "Agent Instructions File",
        default="agent_instructions.txt",
        required=False
    )
    
    print()
    print("🌐 Web Server Configuration:")
    print("-" * 60)
    
    flask_host = get_user_input(
        "Flask Host",
        default="0.0.0.0",
        required=False
    )
    
    flask_port = get_user_input(
        "Flask Port",
        default="5000",
        required=False
    )
    
    flask_debug = get_user_input(
        "Flask Debug Mode (true/false)",
        default="true",
        required=False
    )
    
    # Create .env file
    print()
    print("Creating .env file...")
    
    env_content = f"""# Azure AI Foundry Configuration
# Generated by setup_config.py

# Required: Azure OpenAI/AI Foundry Configuration
AZURE_OPENAI_ENDPOINT={endpoint}

# Authentication Type: "managed_identity" (default) or "api_key"
AZURE_OPENAI_AUTH_TYPE={auth_type}

# Azure OpenAI API Key (only required when AZURE_OPENAI_AUTH_TYPE=api_key)
AZURE_OPENAI_API_KEY={api_key if api_key else ''}
AZURE_OPENAI_DEPLOYMENT_NAME={deployment_name}
AZURE_OPENAI_API_VERSION={api_version}

# Optional: Additional Azure Details
AZURE_SUBSCRIPTION_ID={subscription_id or '<YOUR_AZURE_SUBSCRIPTION_ID>'}
AZURE_RESOURCE_GROUP={resource_group or '<YOUR_RESOURCE_GROUP_NAME>'}
AZURE_AI_PROJECT_NAME={project_name or '<YOUR_AI_PROJECT_NAME>'}

# Agent Configuration
AGENT_NAME={agent_name}
AGENT_INSTRUCTIONS_FILE={instructions_file}

# Web Server Configuration
FLASK_HOST={flask_host}
FLASK_PORT={flask_port}
FLASK_DEBUG={flask_debug}
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print()
    print("✅ Success! Your .env file has been created.")
    print()
    print("Next steps:")
    print("1. (Optional) Create your agent_instructions.txt file")
    print("2. Run 'python app.py' to start the web UI")
    print("   or 'python agent.py' for the CLI interface")
    print()
    print("⚠️  Security Note:")
    print("Never commit your .env file to version control!")
    print("It contains sensitive credentials.")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
